.TH "ImageBuffer" 3 "Fri May 31 2019" "Image Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImageBuffer \- Image Buffer used for holding individual Pixel information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ImageBuffer\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBstackBuffer\fP [1920 *1080]"
.br
.RI "Useful for storing image on stack\&. "
.ti -1c
.RI "unsigned int * \fBheapBuffer\fP"
.br
.RI "Useful for storing images dynamically (i\&.e\&. HD, QHD, 4K) "
.in -1c
.SH "Detailed Description"
.PP 
Buffer that stores pixel data to be used for holding pixel data that is used to write, read, and manipulate Pixel data from images\&. 
.SH "Member Data Documentation"
.PP 
.SS "unsigned int* ImageBuffer::heapBuffer"

.SS "unsigned int ImageBuffer::stackBuffer[ 1920 * 1080]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Image Library from the source code\&.
