.TH "ImageBufferMacros.h" 3 "Fri May 31 2019" "Image Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImageBufferMacros.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBImageWidth\fP   1920"
.br
.ti -1c
.RI "#define \fBImageHeight\fP   1080"
.br
.ti -1c
.RI "#define \fBImageBufferSize\fP   \fBImageWidth\fP * \fBImageHeight\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ImageBufferSize   \fBImageWidth\fP * \fBImageHeight\fP"

.SS "#define ImageHeight   1080"

.SS "#define ImageWidth   1920"

.SH "Author"
.PP 
Generated automatically by Doxygen for Image Library from the source code\&.
